#import "../../preamble/lemmas.typ": *
#import "../../preamble/catt.typ": *
#import "@preview/fletcher:0.5.1" as fletcher: diagram, node, edge

#exercise("1")[In any category $bold(C)$, show that ... is a coproduct diagram just if for...]

#exercise("2")[Show in detail that the free monoid functor $M$ preserves coproducts for any sets $A,B$ ...]

#exercise("3")[Verify that the construction given in the text of the coproduct of monoids $A+B$ as a quotient of the free monoid $M(|A|+|B|)$ really is a coproduct in the category of monoids.]

#exercise("4")[Show that the product of two powerset boolean algebras $cal(P)(A)$ and $cal(P)(B)$ is also a powerset, ...]

#exercise("6")[Verify that the category of monoids has all equalizers and finite products.]

#exercise("10")[In the proof of proposition 3.24 in the text iti s shown that any monoid $M$ has a specific presentation ...]

#exercise("11")[Prove that $Set$ has all coequalizers by constructing the coequalizer of a parallel pair of functions...]

#exercise("12")[Verify the coproduct-coequalizer construction mentioned in the text for coproduct of rooted posets, that is, posets with a least element 0 and monotone....]

#exercise("13")[Show that the category of monoids has all coequalizers as follows...]

#exercise("14")[Consider the following category of sets:]

#exercise("14a")[Given a function $arr(f,A,B)$ describe the equalizer of the function $f comp p_1, f comp p_2 : A times A -> B$ as a binary relation on $A$ and show that it is an equivalence relation called the kernel of $f$]

#exercise("14b")[Show that the kernel of the quotient $A -> A slash R$ by an equivalence relation $R$ is $R$ itself]

#exercise("14c")[Given any binary relation $R subset.eq A times A$, let $[R]$ be the equivalence relation on $A$ generated by $R$. Show that the quotient $A -> A slash [R]$ is the coequalizer of the two projections...]

#exercise("14d")[Using the foregoing, show that for any binary relation $R$ on a set $A$ one can characterize the equivalence relation $[R]$ generated by $R$ as the kernel of the coequalizer of the two projections of $R$.]